#ifndef VSTR__HEADER_H
# error " You must _just_ #include <vstr.h>"
#endif
/*
 *  Copyright (C) 1999, 2000, 2001, 2002  James Antill
 *  
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *   
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *   
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 * 
 *  email: james@and.org
 */

#define VSTR_INIT_REF { vstr_ref_cb_free_nothing, NULL, 0 }

#define VSTR_INIT_IOVEC { NULL, 0, 0 }

#define VSTR_INIT_BASE { NULL, NULL, 0, 0, VSTR_INIT_IOVEC, NULL, NULL, 0, \
 0, 0, 0, 0 \
 0,0,0,0 \
 0,0,0,0,0,0,0,0 \
 0,0,0,0,0,0,0,0 \
 0,0,0,0,0,0,0,0 }

#define VSTR_TYPE_NODE_BUF 1
#define VSTR_TYPE_NODE_NON 2
#define VSTR_TYPE_NODE_PTR 3
#define VSTR_TYPE_NODE_REF 4

#define VSTR_TYPE_ADD_DEF 0
#define VSTR_TYPE_ADD_BUF_PTR 1
#define VSTR_TYPE_ADD_BUF_REF 2
#define VSTR_TYPE_ADD_ALL_REF 3
#define VSTR_TYPE_ADD_ALL_BUF 4

/* aliases to make life more readable */
#define VSTR_TYPE_SUB_DEF VSTR_TYPE_ADD_DEF
#define VSTR_TYPE_SUB_BUF_PTR VSTR_TYPE_ADD_BUF_PTR
#define VSTR_TYPE_SUB_BUF_REF VSTR_TYPE_ADD_BUF_REF
#define VSTR_TYPE_SUB_ALL_REF VSTR_TYPE_ADD_ALL_REF
#define VSTR_TYPE_SUB_ALL_BUF VSTR_TYPE_ADD_ALL_BUF

#define VSTR_FLAG_CONV_UNPRINTABLE_DEF 0
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_NUL (1<<0)
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_BEL (1<<1)
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_BS (1<<2)
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_HT (1<<3)
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_LF (1<<4)
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_VT (1<<5)
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_FF (1<<6)
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_CR (1<<7)
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_DEL (1<<8)
#define VSTR_FLAG_CONV_UNPRINTABLE_ALLOW_HIGH (1<<9)

#define VSTR_TYPE_PARSE_NUM_ERR_NONE 0
#define VSTR_TYPE_PARSE_NUM_ERR_ONLY_S 1
#define VSTR_TYPE_PARSE_NUM_ERR_ONLY_SPM 2
#define VSTR_TYPE_PARSE_NUM_ERR_ONLY_SPMX 3
#define VSTR_TYPE_PARSE_NUM_ERR_PARSE_ERR 4
#define VSTR_TYPE_PARSE_NUM_ERR_OOB 5
#define VSTR_TYPE_PARSE_NUM_ERR_OVERFLOW 6
#define VSTR_TYPE_PARSE_NUM_ERR_NEGATIVE 7

#define VSTR_FLAG_PARSE_NUM_DEF 0
#define VSTR_FLAG_PARSE_NUM_MASK (63) /* (1<<6) - 1 */
#define VSTR_FLAG_PARSE_NUM_LOCAL (1<<6)
#define VSTR_FLAG_PARSE_NUM_SEP (1<<7)
#define VSTR_FLAG_PARSE_NUM_OVERFLOW (1<<8)
#define VSTR_FLAG_PARSE_NUM_SPACE (1<<9)
/* #define VSTR_FLAG_PARSE_NUM_LOC_SEP ???? */

#define VSTR_FLAG_SPLIT_DEF 0
#define VSTR_FLAG_SPLIT_BEG_NULL (1<<0)
#define VSTR_FLAG_SPLIT_MID_NULL (1<<1)
#define VSTR_FLAG_SPLIT_END_NULL (1<<2)
#define VSTR_FLAG_SPLIT_POST_NULL (1<<3)
#define VSTR_FLAG_SPLIT_NO_RET (1<<4)

#define VSTR_FLAG_SECT_FOREACH_DEF 0
#define VSTR_FLAG_SECT_FOREACH_ALLOW_NULL (1<<0)

#define VSTR_TYPE_SECT_FOREACH_DEF 0
#define VSTR_TYPE_SECT_FOREACH_DEL 1
#define VSTR_TYPE_SECT_FOREACH_RET 2

#define VSTR_TYPE_SC_ADD_FD_ERR_NONE 0
#define VSTR_TYPE_SC_ADD_FD_ERR_FSTAT_ERRNO 2
#define VSTR_TYPE_SC_ADD_FD_ERR_MMAP_ERRNO 3
#define VSTR_TYPE_SC_ADD_FD_ERR_MEM 5

#define VSTR_TYPE_SC_ADD_FILE_ERR_NONE 0
#define VSTR_TYPE_SC_ADD_FILE_ERR_OPEN_ERRNO 1
#define VSTR_TYPE_SC_ADD_FILE_ERR_FSTAT_ERRNO 2
#define VSTR_TYPE_SC_ADD_FILE_ERR_MMAP_ERRNO 3
#define VSTR_TYPE_SC_ADD_FILE_ERR_CLOSE_ERRNO 4
#define VSTR_TYPE_SC_ADD_FILE_ERR_MEM 5

#define VSTR_TYPE_SC_READ_FD_ERR_NONE 0
#define VSTR_TYPE_SC_READ_FD_ERR_READ_ERRNO 1
#define VSTR_TYPE_SC_READ_FD_ERR_EOF 2
#define VSTR_TYPE_SC_READ_FD_ERR_MEM 3

#define VSTR_TYPE_SC_WRITE_FD_ERR_NONE 0
#define VSTR_TYPE_SC_WRITE_FD_ERR_WRITE_ERRNO 2
#define VSTR_TYPE_SC_WRITE_FD_ERR_MEM 4

#define VSTR_TYPE_SC_WRITE_FILE_ERR_NONE 0
#define VSTR_TYPE_SC_WRITE_FILE_ERR_OPEN_ERRNO 1
#define VSTR_TYPE_SC_WRITE_FILE_ERR_WRITE_ERRNO 2
#define VSTR_TYPE_SC_WRITE_FILE_ERR_CLOSE_ERRNO 3
#define VSTR_TYPE_SC_WRITE_FILE_ERR_MEM 4

#define VSTR_MAX_NODE_BUF 0xFFFF /* used is 16 bits */
#define VSTR_MAX_NODE_ALL 0xFFFFFFF /* node->len is 28 bits */

#define VSTR__CNTL(x, y) ((VSTR__CNTL_ ## x ## _OFFSET) + (y))

#define VSTR__CNTL_OPT_OFFSET 4000
#define VSTR__CNTL_BASE_OFFSET 5000
#define VSTR__CNTL_CONF_OFFSET 6000

#define VSTR_CNTL_OPT_GET_CONF VSTR__CNTL(OPT, 1)
#define VSTR_CNTL_OPT_SET_CONF VSTR__CNTL(OPT, 2)

#define VSTR_CNTL_BASE_GET_CONF VSTR__CNTL(BASE, 1)
#define VSTR_CNTL_BASE_SET_CONF VSTR__CNTL(BASE, 2)

#define VSTR_CNTL_CONF_GET_NUM_REF VSTR__CNTL(CONF, 1)
/* #define VSTR_CNTL_CONF_SET_NUM_REF VSTR__CNTL(CONF, 2) */
#define VSTR_CNTL_CONF_GET_NUM_IOV_MIN_ALLOC VSTR__CNTL(CONF, 3)
#define VSTR_CNTL_CONF_SET_NUM_IOV_MIN_ALLOC VSTR__CNTL(CONF, 4)
#define VSTR_CNTL_CONF_GET_NUM_IOV_MIN_OFFSET VSTR__CNTL(CONF, 5)
#define VSTR_CNTL_CONF_SET_NUM_IOV_MIN_OFFSET VSTR__CNTL(CONF, 6)
#define VSTR_CNTL_CONF_GET_NUM_BUF_SZ VSTR__CNTL(CONF, 7)
#define VSTR_CNTL_CONF_SET_NUM_BUF_SZ VSTR__CNTL(CONF, 8)
/* more nums ... */
#define VSTR_CNTL_CONF_GET_FLAG_MALLOC_BAD VSTR__CNTL(CONF, 21)
#define VSTR_CNTL_CONF_SET_FLAG_MALLOC_BAD VSTR__CNTL(CONF, 22)
