/* DO NOT EDIT THIS FILE */
#ifdef USE_WRAP_MEMCPY
#define vstr_nx_wrap_memcpy vstr_wrap_memcpy
#endif

#ifdef USE_WRAP_MEMCMP
#define vstr_nx_wrap_memcmp vstr_wrap_memcmp
#endif

#ifdef USE_WRAP_MEMCHR
#define vstr_nx_wrap_memchr vstr_wrap_memchr
#endif

#ifdef USE_WRAP_MEMRCHR
#define vstr_nx_wrap_memrchr vstr_wrap_memrchr
#endif

#ifdef USE_WRAP_MEMSET
#define vstr_nx_wrap_memset vstr_wrap_memset
#endif

#ifdef USE_WRAP_MEMMOVE
#define vstr_nx_wrap_memmove vstr_wrap_memmove
#endif

#define vstr_nx_ref_del vstr_ref_del
#define vstr_nx_ref_add vstr_ref_add
#define vstr_nx_cache_get vstr_cache_get
#define vstr_nx_cache__pos vstr_cache__pos
#define vstr_nx_base__pos vstr_base__pos
#define vstr_nx_export__node_ptr vstr_export__node_ptr
#define vstr_nx_export_chr vstr_export_chr
#define vstr_nx_iter_fwd_beg vstr_iter_fwd_beg
#define vstr_nx_iter_fwd_nxt vstr_iter_fwd_nxt
#define vstr_nx_add_buf vstr_add_buf
#define vstr_nx_del vstr_del
#define vstr_nx_sects_add vstr_sects_add
#define vstr_nx_add_rep_chr vstr_add_rep_chr
