/* include/autoconf.h.  Generated automatically by configure.  */
/* auto maticaly */
#define VSTR_AUTOCONF_STDC_HEADERS 1

#define VSTR_AUTOCONF_TIME_WITH_SYS_TIME 1

/* #undef HAVE_SYS_TIME_H */


#define VSTR_AUTOCONF_HAVE_MALLOC_H 1

#define VSTR_AUTOCONF_HAVE_SYS_POLL_H 1

#define VSTR_AUTOCONF_HAVE_SYS_MMAN_H 1

#define VSTR_AUTOCONF_HAVE_DLFCN_H 1

#define VSTR_AUTOCONF_HAVE_TERMCAP_H 1

/* #undef USE_NCURSES_DB */

/* #undef HAVE_SYS_FILIO_H */

#define VSTR_AUTOCONF_HAVE_SYS_UIO_H 1

#define VSTR_AUTOCONF_HAVE_SYS_UN_H 1

#define VSTR_AUTOCONF_HAVE_ZLIB_H 1

#define VSTR_AUTOCONF_HAVE_SYS_PRCTL_H 1


/* #undef const */


/* #undef mode_t */
/* #undef off_t */
/* #undef pid_t */
/* #undef size_t */
/* #undef ssize_t */
/* #undef uid_t */
/* #undef gid_t */
/* #undef ptrdiff_t */
/* #undef intmax_t */
/* #undef uintmax_t */
#define VSTR_AUTOCONF_HAVE_LONG_LONG 1

/* auto macors... */
#define VSTR_AUTOCONF_HAVE_UNISTD_H 1
#define VSTR_AUTOCONF_HAVE_MMAP 1
#define VSTR_AUTOCONF_HAVE_ALLOCA_H 1
#define VSTR_AUTOCONF_HAVE_ALLOCA 1
#define VSTR_AUTOCONF_HAVE_MMAP 1
#define VSTR_AUTOCONF_HAVE_STRFTIME 1
/* #undef HAVE_VFORK_H */
/* #undef vfork */
#define VSTR_AUTOCONF_HAVE_VPRINTF 1


#define VSTR_AUTOCONF_HAVE_MEMCHR 1

#define VSTR_AUTOCONF_HAVE_MEMCPY 1

#define VSTR_AUTOCONF_HAVE_MEMCMP 1

#define VSTR_AUTOCONF_HAVE_STRSPN 1

#define VSTR_AUTOCONF_HAVE_STRCSPN 1

#define VSTR_AUTOCONF_HAVE_STPCPY 1

#define VSTR_AUTOCONF_HAVE_STRNCMP 1

#define VSTR_AUTOCONF_HAVE_STRCASECMP 1

#define VSTR_AUTOCONF_HAVE_STRNCASECMP 1

#define VSTR_AUTOCONF_HAVE_STRNLEN 1

/* #undef HAVE_STRNCHR */

#define VSTR_AUTOCONF_HAVE_ASPRINTF 1

#define VSTR_AUTOCONF_HAVE_VSNPRINTF 1


#define VSTR_AUTOCONF_HAVE_GETOPT_LONG 1

#define VSTR_AUTOCONF_HAVE_SIGEMPTYSET 1

#define VSTR_AUTOCONF_HAVE_DIFFTIME 1

#define VSTR_AUTOCONF_HAVE_SIGACTION 1

#define VSTR_AUTOCONF_HAVE_STRERROR 1


#define VSTR_AUTOCONF_HAVE_INET_NTOP 1

#define VSTR_AUTOCONF_HAVE_INET_NTOA 1

#define VSTR_AUTOCONF_HAVE_INET_PTON 1

#define VSTR_AUTOCONF_HAVE_INET_ATON 1

#define VSTR_AUTOCONF_HAVE_INET_ADDR 1

#define VSTR_AUTOCONF_HAVE_PREAD 1


#define VSTR_AUTOCONF_HAVE_OFFSETOF 1

#define VSTR_AUTOCONF_HAVE_VA_COPY 1

#define VSTR_AUTOCONF_HAVE___VA_COPY 1

#define VSTR_AUTOCONF_HAVE_POLL 1

#define VSTR_AUTOCONF_HAVE_WRITEV 1

#define VSTR_AUTOCONF_HAVE_DL_RTLD_GLOBAL 1

#define VSTR_AUTOCONF_HAVE_C9X_SNPRINTF 1

#define VSTR_AUTOCONF_HAVE_SETRLIMIT 1

#define VSTR_AUTOCONF_HAVE_PRCTL 1

#define VSTR_AUTOCONF_HAVE_SIGCONTEXT 1

#define VSTR_AUTOCONF_HAVE_OLD_SIGCONTEXT 1

#define VSTR_AUTOCONF_HAVE_MALLINFO 1

/* #undef HAVE_DECL_TERMCAP_VARS */

#define VSTR_AUTOCONF_USE_QUICK_ADD_TIME 1

#define VSTR_AUTOCONF_HAVE_SIGALTSTACK 1

/* #undef HAVE_C9x_STRUCT_HACK */

#define VSTR_AUTOCONF_HAVE_CMSGHDR_STRUCT 1

#define VSTR_AUTOCONF_HAVE_CMSGHDR_RIGHTS 1

#define VSTR_AUTOCONF_HAVE_CMSGHDR_CREDENTIALS 1

#define VSTR_AUTOCONF_HAVE_SO_PEERCREDS 1

#define VSTR_AUTOCONF_HAVE_TCP_CORK 1

#define VSTR_AUTOCONF_HAVE_CMSG_DATA 1

#define VSTR_AUTOCONF_HAVE_SENDFILE 1

/* #undef HAVE_SENDFILE_FREEBSD */

#define VSTR_AUTOCONF_HAVE_SOCKADDR_IN6 1

#define VSTR_AUTOCONF_ULONG_MAX_LEN 10

#define VSTR_AUTOCONF_NDEBUG 1
