/* DO NOT EDIT THIS FILE */
#ifdef USE_WRAP_MEMCPY
VSTR__SYM(wrap_memcpy)
#endif

#ifdef USE_WRAP_MEMCMP
VSTR__SYM(wrap_memcmp)
#endif

#ifdef USE_WRAP_MEMCHR
VSTR__SYM(wrap_memchr)
#endif

#ifdef USE_WRAP_MEMRCHR
VSTR__SYM(wrap_memrchr)
#endif

#ifdef USE_WRAP_MEMSET
VSTR__SYM(wrap_memset)
#endif

#ifdef USE_WRAP_MEMMOVE
VSTR__SYM(wrap_memmove)
#endif

VSTR__SYM(ref_del)
VSTR__SYM(ref_add)
VSTR__SYM(cache_get)
VSTR__SYM(cache__pos)
VSTR__SYM(base__pos)
VSTR__SYM(export__node_ptr)
VSTR__SYM(export_chr)
VSTR__SYM(iter_fwd_beg)
VSTR__SYM(iter_fwd_nxt)
VSTR__SYM(add_buf)
VSTR__SYM(del)
VSTR__SYM(sects_add)
VSTR__SYM(add_rep_chr)
