/* DO NOT EDIT THIS FILE */
#ifdef USE_WRAP_MEMCPY
#undef vstr_wrap_memcpy
#endif

#ifdef USE_WRAP_MEMCMP
#undef vstr_wrap_memcmp
#endif

#ifdef USE_WRAP_MEMCHR
#undef vstr_wrap_memchr
#endif

#ifdef USE_WRAP_MEMRCHR
#undef vstr_wrap_memrchr
#endif

#ifdef USE_WRAP_MEMSET
#undef vstr_wrap_memset
#endif

#ifdef USE_WRAP_MEMMOVE
#undef vstr_wrap_memmove
#endif

#undef vstr_ref_del
#undef vstr_ref_add
#undef vstr_cache_get
#undef vstr_cache__pos
#undef vstr_base__pos
#undef vstr_export__node_ptr
#undef vstr_export_chr
#undef vstr_iter_fwd_beg
#undef vstr_iter_fwd_nxt
#undef vstr_add_buf
#undef vstr_del
#undef vstr_sects_add
#undef vstr_add_rep_chr
