/* DO NOT EDIT THIS FILE */
#ifdef USE_WRAP_MEMCPY
#define vstr_wrap_memcpy vstr_nx_wrap_memcpy
#endif

#ifdef USE_WRAP_MEMCMP
#define vstr_wrap_memcmp vstr_nx_wrap_memcmp
#endif

#ifdef USE_WRAP_MEMCHR
#define vstr_wrap_memchr vstr_nx_wrap_memchr
#endif

#ifdef USE_WRAP_MEMRCHR
#define vstr_wrap_memrchr vstr_nx_wrap_memrchr
#endif

#ifdef USE_WRAP_MEMSET
#define vstr_wrap_memset vstr_nx_wrap_memset
#endif

#ifdef USE_WRAP_MEMMOVE
#define vstr_wrap_memmove vstr_nx_wrap_memmove
#endif

#define vstr_ref_del vstr_nx_ref_del
#define vstr_ref_add vstr_nx_ref_add
#define vstr_cache_get vstr_nx_cache_get
#define vstr_cache__pos vstr_nx_cache__pos
#define vstr_base__pos vstr_nx_base__pos
#define vstr_export__node_ptr vstr_nx_export__node_ptr
#define vstr_export_chr vstr_nx_export_chr
#define vstr_iter_fwd_beg vstr_nx_iter_fwd_beg
#define vstr_iter_fwd_nxt vstr_nx_iter_fwd_nxt
#define vstr_add_buf vstr_nx_add_buf
#define vstr_del vstr_nx_del
#define vstr_sects_add vstr_nx_sects_add
#define vstr_add_rep_chr vstr_nx_add_rep_chr
